apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: crudapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-mysql
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done",
            ]
      containers:
        - name: api
          image: crudapp-api:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DB_CONNECTION_STRING
              value: server=mysql;port=3306;database=crudapp;user=root;password=secret
            - name: CLIENT_URL
              value: http://localhost:30073,http://127.0.0.1:30073
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8080
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: crudapp
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
