apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: crudapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: crudapp-client:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: crudapp
spec:
  selector:
    app: client
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30073
