FROM nginx:alpine

# Copy nginx configuration
COPY nginx/api.conf /etc/nginx/conf.d/default.conf

# Copy SSL certificates
COPY ssl /etc/nginx/ssl

# Expose HTTPS port
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]

